### ISSUE TITLE
Error: IFrame removed from DOM during signinSilent

### ISSUE THREAD

**Issue by MFredX** [authts/oidc-client-ts#1059]
I have enabled `automaticSilentRenew` on my Angular app and I am able to renew my session without any issues. However I saw this error being logged on my console during the silent sign in process. I was wondering if this means there is something wrong with how I have implemented my silent sign in. 

```
[Event('Window navigation aborted')] raise: Error: IFrame removed from DOM
    at HTMLIFrameElement.<anonymous> (oidc-client-ts.js:2141:29)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23888:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23888:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Object.onInvokeTask (core.mjs:24189:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
```

I am implementing the Silent Sign In via an Angular component that has no HTML template. Wonder if that is what is causing this iframe error.

Here are my logs if that helps;

```
[Timer('Access token expiring')] init: using duration 1
VM89 vendor.js:165681 [UserManagerEvents] load: registering expired timer, raising in 54 seconds
VM89 vendor.js:165681 [Timer('Access token expired')] init: begin
VM89 vendor.js:165681 [Timer('Access token expired')] cancel: begin
VM89 vendor.js:165681 [Timer('Access token expired')] init: using duration 54
VM89 vendor.js:165686 [UserManager] getUser: user loaded
VM89 vendor.js:165681 [UserManagerEvents] load: begin
VM89 vendor.js:165681 [UserManagerEvents] load: access token present, remaining duration: 53
VM89 vendor.js:165681 [UserManagerEvents] load: registering expiring timer, raising in 1 seconds
VM89 vendor.js:165681 [Timer('Access token expiring')] init: begin
VM89 vendor.js:165681 [Timer('Access token expiring')] init: skipping since already initialized for expiration at 1687410485
VM89 vendor.js:165681 [UserManagerEvents] load: registering expired timer, raising in 54 seconds
VM89 vendor.js:165681 [Timer('Access token expired')] init: begin
VM89 vendor.js:165681 [Timer('Access token expired')] init: skipping since already initialized for expiration at 1687410538
VM90 main.js:33099 got user succesfully
VM89 vendor.js:165681 [UserManager] signinSilentCallback: begin
VM89 vendor.js:165681 [IFrameNavigator] callback: begin
VM89 vendor.js:165686 [UserManager] signinSilentCallback: success
oidc-client-ts.js:48 [IFrameWindow] navigate: got response from window
oidc-client-ts.js:48 [IFrameWindow] _dispose: begin
oidc-client-ts.js:48 [UserManager] _signinEnd: begin
oidc-client-ts.js:48 [OidcClient] processSigninResponse: begin
oidc-client-ts.js:48 [OidcClient] readSigninResponseState: begin
oidc-client-ts.js:48 [WebStorageStateStore] remove('194296cbee11450cb1df4da1944e5a6b'): begin
oidc-client-ts.js:48 [SigninState.fromStorageString] begin
oidc-client-ts.js:48 [OidcClient] processSigninResponse: received state from storage; validating response
oidc-client-ts.js:48 [ResponseValidator] validateSigninResponse: begin
oidc-client-ts.js:48 [ResponseValidator] _processSigninState: begin
oidc-client-ts.js:48 [ResponseValidator] _processSigninState: state validated
oidc-client-ts.js:48 [ResponseValidator] validateSigninResponse: state processed
oidc-client-ts.js:48 [ResponseValidator] _processCode: begin
oidc-client-ts.js:48 [ResponseValidator] _processCode: Validating code
oidc-client-ts.js:48 [TokenClient] exchangeCode: begin
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('token_endpoint'): begin
oidc-client-ts.js:48 [MetadataService] getMetadata: begin
oidc-client-ts.js:48 [MetadataService] getMetadata: using cached values
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('token_endpoint'): resolved
oidc-client-ts.js:48 [TokenClient] exchangeCode: got token endpoint
oidc-client-ts.js:48 [JsonService] postForm: begin
oidc-client-ts.js:48 [JsonService] appendExtraHeaders: begin
oidc-client-ts.js:48 [JsonService] postForm: url: https://my.identity.service.com/identity/connect/token
oidc-client-ts.js:48 [Event('Window navigation aborted')] raise: Error: IFrame removed from DOM
    at HTMLIFrameElement.<anonymous> (oidc-client-ts.js:2141:29)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23888:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23888:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Object.onInvokeTask (core.mjs:24189:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
oidc-client-ts.js:48 [JsonService] postForm: HTTP response received, status 200
oidc-client-ts.js:48 [TokenClient] exchangeCode: got response
oidc-client-ts.js:48 [ResponseValidator] validateSigninResponse: code processed
oidc-client-ts.js:48 [ResponseValidator] _validateIdTokenAttributes: begin
oidc-client-ts.js:48 [ResponseValidator] _validateIdTokenAttributes: decoding ID Token JWT
oidc-client-ts.js:48 [ResponseValidator] validateSigninResponse: tokens validated
oidc-client-ts.js:48 [ResponseValidator] _processClaims: begin
oidc-client-ts.js:48 [ResponseValidator] _processClaims: loading user info
oidc-client-ts.js:48 [UserInfoService] getClaims: begin
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('userinfo_endpoint'): begin
oidc-client-ts.js:48 [MetadataService] getMetadata: begin
oidc-client-ts.js:48 [MetadataService] getMetadata: using cached values
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('userinfo_endpoint'): resolved
oidc-client-ts.js:48 [UserInfoService] getClaims: got userinfo url https://my.identity.service.com/identity/connect/userinfo
oidc-client-ts.js:48 [JsonService] getJson: begin
oidc-client-ts.js:48 [JsonService] getJson: token passed, setting Authorization header
oidc-client-ts.js:48 [JsonService] appendExtraHeaders: begin
oidc-client-ts.js:48 [JsonService] getJson: url: https://my.identity.service.com/identity/connect/userinfo
oidc-client-ts.js:48 [JsonService] getJson: HTTP response received, status 200
oidc-client-ts.js:48 [UserInfoService] getClaims: got claims {xxxxxxxxxx}
oidc-client-ts.js:48 [ResponseValidator] _processClaims: user info claims received from user info endpoint
oidc-client-ts.js:48 [ResponseValidator] _processClaims: user info claims received, updated profile: {iss: 'https://my.identity.service.com/identity', iat: 1687410482, exp: 1687410782, aud: 'xxxxxxxx', sid: '23C17D9E2CC7CAA258B2FE550FE89431', …}
oidc-client-ts.js:48 [ResponseValidator] validateSigninResponse: claims processed
oidc-client-ts.js:48 [UserManager] _signinEnd: got signin response
oidc-client-ts.js:48 [UserManager] _buildUser: begin
oidc-client-ts.js:48 [UserManager] _buildUser: current user matches user returned from signin
oidc-client-ts.js:48 [UserManager] storeUser: begin
oidc-client-ts.js:48 [UserManager] storeUser: storing user
oidc-client-ts.js:48 [User] toStorageString: begin
oidc-client-ts.js:48 [WebStorageStateStore] set('user:https://my.identity.service.com/identity:my:client'): begin
oidc-client-ts.js:48 [UserManager] _buildUser: user stored
oidc-client-ts.js:48 [UserManagerEvents] load: begin
oidc-client-ts.js:48 [UserManagerEvents] load: access token present, remaining duration: 120
oidc-client-ts.js:48 [UserManagerEvents] load: registering expiring timer, raising in 60 seconds
```

**Comment by pamapa** [comment]
Its coming from here:
https://github.com/authts/oidc-client-ts/blob/6cb34ab9d128e4a2a7a6e1b35976f912d52008c6/src/navigators/IFrameWindow.ts#L58-L71

You will need to debug...

**Comment by MFredX** [comment]
This seems to be something that's logged within the internal logic of the library, it does not surface during the execution. After I turned off my logs I wasn't able to replicate or see this error. 

I would have expected an error to have being thrown from the `UserManager.signinSilentCallback` if there was something wrong with my implementation, however the promise returned by `signinSilentCallback` resolved succesfully for me. 

I was hoping for some clarification as to why this was an internally error logged, perhaps this is insignificant.

**Comment by pamapa** [comment]
`this._abort.raise` is used for the communication between the iframe window and the parent window. Such that the parent window can dispose stuff related to that iframe.

**Comment by MFredX** [comment]
I don't think I understood you. 

Is this `abort.raised` error something to be concerned?

**Comment by pamapa** [comment]
> Is this `abort.raised` error something to be concerned?

no

**Comment by MFredX** [comment]
I'm sure there are lot of enhancements on the backlog of this project. 

However, would it be worth modifying that logic to not be logged as an error? 

It would definitely improve the developer experience, as the current implementation implies something is wrong in the background when referring the logs. Just thought I'd mention that.

**Comment by pamapa** [comment]
i think normally this should not be logged, but in your case it does, i am not sure why. this needs some debugging...

**Comment by MFredX** [comment]
Couldn't make head way with this bug. However, I tried to isolate this from my app and I have been able to replicate this in the sample Angular app mentioned in the library's docs.

I've forked and updated the sample angular app with the latest client package and did some tidy up; https://github.com/MFredX/sample-angular-oidc-client-ts

To replicate the issue, you can swap in your own Identity Service properties and click on the `Renew Token` button after having signed in. You will then be able to see this issue in the Console (I've enabled logging).

On an unrelated note, I can update the existing sample angular app with this as it has some improvements.

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
