### ISSUE TITLE
login_required error in web browser console when calling signinRedirectCallback

### ISSUE THREAD

**Issue by quan1997ap** [authts/oidc-client-ts#1450]
Hi team. Thank for your library. I'm using your lib in my project.
I have issue with refeshToken. After user login, following error occurred twice in the web browser console:
```
ErrorResponse: login_required
    at ResponseValidator._processSigninState (http://localhost:4200/vendor.js:112250:13)
    at http://localhost:4200/vendor.js:112141:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:4200/vendor.js:116388:24)
    at _next (http://localhost:4200/vendor.js:116410:9)
    at http://localhost:4200/vendor.js:116417:7
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:13207:21)
    at http://localhost:4200/vendor.js:116406:12
    at ResponseValidator.validateSigninResponse (http://localhost:4200/vendor.js:112154:7)
    at http://localhost:4200/vendor.js:112897:32
```

I can't fix it. Can you help me. Thanks.
Sorry about my english.

**Comment by pamapa** [comment]
Looks like your IdP is not happy with the refresh token you pass back...

**Comment by quan1997ap** [comment]
> Looks like your IdP is not happy with the refresh token you pass back...

How can I fix it? It only keycloak config right?
