### ISSUE TITLE
IFrame timed out without a response, how to debug it?

### ISSUE THREAD

**Issue by kostia-lev** [authts/oidc-client-ts#975]
I use oidc-client-ts in outlook and see this error during silent signin. How to debug such issue?

[MetadataService] using fetchRequestCredentials from settings
oidc-client-ts.js:48 [UserManager] signinSilent: begin
oidc-client-ts.js:48 [UserManager] _loadUser: begin
oidc-client-ts.js:48 [WebStorageStateStore] get('user:https://localhost:44301:parsnipsOutLookAddinTest'): begin
oidc-client-ts.js:48 [UserManager] _loadUser: user storageString loaded
oidc-client-ts.js:48 [User.fromStorageString] begin
oidc-client-ts.js:48 [UserManager] _signinStart: begin
oidc-client-ts.js:48 [OidcClient] createSigninRequest: begin
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('authorization_endpoint'): begin
oidc-client-ts.js:48 [MetadataService] getMetadata: begin
oidc-client-ts.js:48 [MetadataService] getMetadata: getting metadata from https://localhost:44301/.well-known/openid-configuration
oidc-client-ts.js:48 [JsonService] getJson: begin
oidc-client-ts.js:48 [JsonService] getJson: url: https://localhost:44301/.well-known/openid-configuration
oidc-client-ts.js:48 [JsonService] getJson: HTTP response received, status 200
oidc-client-ts.js:48 [MetadataService] getMetadata: merging remote JSON with seed metadata
oidc-client-ts.js:48 [MetadataService] _getMetadataProperty('authorization_endpoint'): resolved
oidc-client-ts.js:48 [OidcClient] createSigninRequest: Received authorization endpoint https://localhost:44301/connect/authorize
oidc-client-ts.js:48 [OidcClient] clearStaleState: begin
oidc-client-ts.js:48 [State.clearStaleState] begin
oidc-client-ts.js:48 [WebStorageStateStore] getAllKeys: begin
oidc-client-ts.js:48 [State.clearStaleState] got keys ['user:https://localhost:44301:parsnipsOutLookAddinTest']
oidc-client-ts.js:48 [WebStorageStateStore] get('user:https://localhost:44301:parsnipsOutLookAddinTest'): begin
oidc-client-ts.js:48 [State.fromStorageString] begin
oidc-client-ts.js:48 [State.clearStaleState] got item from key: user:https://localhost:44301:parsnipsOutLookAddinTest 1682001064
oidc-client-ts.js:48 [SigninState] toStorageString: begin
oidc-client-ts.js:48 [WebStorageStateStore] set('a259726b07784fa7b764880dcb15138e'): begin
oidc-client-ts.js:48 [UserManager] _signinStart: got signin request
oidc-client-ts.js:48 [IFrameWindow] navigate: Using timeout of: 10
oidc-client-ts.js:48 [IFrameWindow] navigate: begin
oidc-client-ts.js:48 [IFrameWindow] navigate: setting URL in window
oidc-client-ts.js:48 [Timer('Access token expiring')] timer completes in 173
oidc-client-ts.js:48 [Timer('Access token expired')] timer completes in 234
oidc-client-ts.js:48 [Timer('Access token expiring')] timer completes in 168
oidc-client-ts.js:48 [Timer('Access token expired')] timer completes in 229
oidc-client-ts.js:48 [Event('Window navigation aborted')] raise: ErrorTimeout: IFrame timed out without a response
    at https://localhost:3003/authentication.js:135120:54
oidc-client-ts.js:48 [IFrameWindow] _dispose: begin
oidc-client-ts.js:48 [UserManager] _signinStart: error after preparing navigator, closing navigator window
oidc-client-ts.js:48 [Event('Window navigation aborted')] raise: Error: IFrame removed from DOM
    at HTMLIFrameElement.<anonymous> (oidc-client-ts.js:1993:1)

**Comment by kostia-lev** [comment]
I solved myself, error was in oidc-silent-redirect.html. I incorrectly called silentredirectcallback
